---
# tasks file for ansible-role-sensu-api

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ sensu-api_log_dir }}"
    mode: 0755
    owner: "{{ sensu-api_user }}"
    group: "{{ sensu-api_group }}"
    state: directory
  notify: Restart sensu-api

- name: Create db directory
  file:
    path: "{{ sensu-api_db_dir }}"
    mode: 0755
    owner: "{{ sensu-api_user }}"
    group: "{{ sensu-api_group }}"
    state: directory
  notify: Restart sensu-api

- name: Create sensu-api.conf
  template:
    src: sensu-api.conf.j2
    dest: "{{ sensu-api_conf_file }}"
    validate: echo %s
  notify: Restart sensu-api

- name: Start sensu-api
  service:
    name: "{{ sensu-api_service }}"
    enabled: true
    state: started
