---
# tasks file for ansible-role-sensu_api

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create sensu_api_conf_d_dir
  file:
    path: "{{ sensu_api_conf_d_dir }}"
    state: directory

- name: Create sensu_api_extensions_dir
  file:
    path: "{{ sensu_api_extensions_dir }}"
    state: directory

- name: Create sensu_api_plugins_dir
  file:
    path: "{{ sensu_api_plugins_dir }}"
    state: directory

- name: Create sensu_api_config_file
  template:
    src: config.json.j2
    dest: "{{ sensu_api_config_file }}"
    validate: "python -c 'import sys; import json; json.loads(open(sys.argv[1]).read())' %s"
  notify: Restart sensu services

- name: Create json files
  template:
    src: json.j2
    dest: "{{ sensu_api_conf_d_dir }}/{{ item }}.json"
    validate: "python -c 'import sys; import json; json.loads(open(sys.argv[1]).read())' %s"
  notify: Restart sensu services
  with_items: "{{ sensu_api_config_fragments }}"


- name: Start sensu_api_service
  service:
    name: "{{ sensu_api_service }}"
    enabled: true
    state: started
