---

- name: Restart sensu_api_service
  service:
    name: "{{ sensu_api_service }}"
    state: restarted

- name: Restart sensu services
  service:
    name: "{{ sensu_api_service }}"
    state: restarted
  listen: "Restart sensu services"
